#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Volumes/Work/Data/FlutterSDK/flutter"
export "FLUTTER_APPLICATION_PATH=/Volumes/Work/Work/Flutter/jiangxing/travel_hour_client"
export "FLUTTER_TARGET=/Volumes/Work/Work/Flutter/jiangxing/travel_hour_client/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Volumes/Work/Data/FlutterSDK/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=2.0.0"
export "FLUTTER_BUILD_NUMBER=7"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
